name: deploy-test
on:
     push:
        branches:
        - main
jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
              with:
                fetch-depth: 0
            - name: Setup node 
              uses: actions/setup-node@v2
              with:
                node-version: '18'
            - name: Dependencias
              run: npm install
            - name: Lint
              run: npm run eslint    


